server:
  port: 8083
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.226.128:3306/guli_wms
    username: root
    password: 1234
  redis:
    host: 192.128.226.128
mybatis-plus:
  mapper-locations: classpath:mapper/wms/**/*.xml
